/* useAsync.run is stable across renders. */
/* oxlint-disable react-hooks/exhaustive-deps */
import type { ThemeType } from "@shared/types";
import { ArrowLeft, ArrowUpRight, Check, Download, ShoppingBag } from "lucide-react";
import { useEffect } from "react";
import { Link, useParams } from "react-router-dom";
import Header from "../components/header";
import { ErrorMessage } from "../components/ui/error-message";
import { Skeleton } from "../components/ui/skeleton";
import { useAppAuth } from "../context/auth-store";
import { useCart } from "../context/cart-store";
import { useAsync } from "../hooks/use-async";
import { api } from "../lib/api";
import { money } from "../lib/format";

export default function ThemeDetailPage() { const { slug } = useParams(); const request = useAsync<ThemeType>(); const cart = useCart(); const { user } = useAppAuth(); useEffect(() => { if (slug) void request.run(api.get<ThemeType>(`/themes/${slug}`)).catch(() => undefined); }, [slug, request.run]); if (request.isLoading && !request.data) return <><Header /><main className="detail-page"><Skeleton className="detail-skeleton" /></main></>; if (request.error || !request.data) return <><Header /><main className="centered-state"><ErrorMessage message={request.error ?? "Theme not found"} /><Link to="/themes">Back to themes</Link></main></>; const theme = request.data; const image = theme.images[0]?.variants?.at(-1)?.url ?? theme.images[0]?.url; return <div className="store-page"><Header /><main className="detail-page"><Link className="back-link" to="/themes"><ArrowLeft size={16} />All themes</Link><section className="detail-hero"><div className="detail-copy"><div className="theme-card-meta"><div>{theme.stack.map((item) => <span key={item}>{item}</span>)}</div></div><h1>{theme.name}</h1><p>{theme.description}</p><div className="detail-actions"><strong>{money(theme.priceMinor, theme.currency)}</strong>{theme.purchased ? <Link className="primary-button" to="/purchases"><Download size={17} />Open your library</Link> : user?.role === "admin" ? null : theme.canPurchase === false ? <button className="primary-button" disabled title="The download package has not been uploaded yet"><ShoppingBag size={17} />Coming soon</button> : user ? <button className="primary-button" disabled={cart.isLoading} onClick={() => void cart.add(theme.id).catch(() => undefined)}><ShoppingBag size={17} />Add to cart</button> : <Link className="primary-button" to="/sign-in">Sign in to purchase</Link>}<a className="secondary-button" href={theme.previewUrl} target="_blank" rel="noreferrer">Live preview <ArrowUpRight size={16} /></a></div></div><div className="detail-preview">{image ? <img src={image} alt={`Large preview of ${theme.name}`} /> : <span>{theme.name}</span>}</div></section><section className="detail-info"><article><span className="eyebrow">What’s included</span><h2>Everything you need to launch.</h2><ul>{theme.features.map((feature) => <li key={feature}><Check size={16} />{feature}</li>)}</ul></article><aside><dl><div><dt>Version</dt><dd>{theme.version}</dd></div><div><dt>License</dt><dd>Single portfolio</dd></div><div><dt>Downloads</dt><dd>{theme.canPurchase === false ? "Not available yet" : "5 secure downloads"}</dd></div><div><dt>Delivery</dt><dd>{theme.canPurchase === false ? "Package coming soon" : "Immediate after payment"}</dd></div></dl></aside></section></main></div>; }
