import { randomBytes } from "node:crypto";
import { raw, Router } from "express";
import DiscountModel from "../models/discount.ts";
import { requireAdmin, requireDatabaseUser } from "../middlewares/auth.ts";
import { rateLimit } from "../middlewares/rate-limit.ts";
import { discountInputSchema, discountPatchSchema, idSchema, parseOrThrow, themeInputSchema, themePatchSchema, uploadCompleteSchema, uploadInitSchema, uploadPartSchema } from "../schemas/marketplace.ts";
import { audit } from "../services/audit.service.ts";
import { getAdminOrder, listAdminOrders, marketplaceInsights, themeSales } from "../services/order.service.ts";
import { archiveOrDeleteTheme, createTheme, getAdminTheme, listAdminThemes, publishTheme, updateTheme } from "../services/theme.service.ts";
import { cancelUpload, completeUpload, initiateUpload, uploadPart } from "../services/upload.service.ts";
import { AppError } from "../utils/app-error.ts";

const router = Router(); router.use(requireDatabaseUser, requireAdmin);

router.get("/insights", async (req, res, next) => { try { const allowed = ["day", "week", "month", "six_months", "year"] as const; const period = allowed.includes(req.query.period as typeof allowed[number]) ? req.query.period as typeof allowed[number] : "month"; res.json({ success: true, data: await marketplaceInsights(period, req.query.from ? String(req.query.from) : undefined, req.query.to ? String(req.query.to) : undefined) }); } catch (error) { next(error); } });

router.get("/themes", async (req, res, next) => { try { res.json({ success: true, data: await listAdminThemes(req.query) }); } catch (error) { next(error); } });
router.get("/themes/:id", async (req, res, next) => { try { const { id } = parseOrThrow(idSchema, req.params); res.json({ success: true, data: await getAdminTheme(id) }); } catch (error) { next(error); } });
router.post("/themes", async (req, res, next) => { try { const input = parseOrThrow(themeInputSchema, req.body); const theme = await createTheme(req.currentUser!._id, input); await audit(req, "theme.create", "theme", String(theme._id), undefined, theme.toObject()); res.status(201).json({ success: true, data: await getAdminTheme(String(theme._id)), message: "Theme created as draft" }); } catch (error) { next(error); } });
router.put("/themes/:id", async (req, res, next) => { try { const { id } = parseOrThrow(idSchema, req.params); const before = await getAdminTheme(id); const theme = await updateTheme(id, req.currentUser!._id, parseOrThrow(themeInputSchema, req.body)); await audit(req, "theme.update", "theme", id, before, theme.toObject()); res.json({ success: true, data: await getAdminTheme(id), message: "Theme updated" }); } catch (error) { next(error); } });
router.post("/themes/:id/publish", async (req, res, next) => { try { const { id } = parseOrThrow(idSchema, req.params); const published = req.body.published !== false; const theme = await publishTheme(id, published); await audit(req, published ? "theme.publish" : "theme.unpublish", "theme", id, undefined, { status: theme.status }); res.json({ success: true, data: await getAdminTheme(id), message: published ? "Theme published" : "Theme returned to draft" }); } catch (error) { next(error); } });
router.delete("/themes/:id", async (req, res, next) => { try { const { id } = parseOrThrow(idSchema, req.params); const result = await archiveOrDeleteTheme(id); await audit(req, result.archived ? "theme.archive" : "theme.delete", "theme", id); res.json({ success: true, data: result, message: result.archived ? "Theme archived because it has sales" : "Theme deleted" }); } catch (error) { next(error); } });

router.post("/uploads/initiate", rateLimit("upload-init", 30, 60_000, true), async (req, res, next) => { try { res.status(201).json({ success: true, data: await initiateUpload(req.currentUser!._id, parseOrThrow(uploadInitSchema, req.body)) }); } catch (error) { next(error); } });
router.put("/uploads/:id/parts/:partNumber", rateLimit("upload-parts", 300, 60_000, true), raw({ type: "application/octet-stream", limit: "8mb" }), async (req, res, next) => { try { const { id } = parseOrThrow(idSchema, req.params); const { partNumber } = parseOrThrow(uploadPartSchema, { partNumber: Number(req.params.partNumber) }); if (!Buffer.isBuffer(req.body)) throw new AppError(400, "INVALID_UPLOAD_PART", "The file part could not be read"); const ETag = await uploadPart(id, req.currentUser!._id, partNumber, req.body); res.json({ success: true, data: { ETag } }); } catch (error) { next(error); } });
router.post("/uploads/:id/complete", async (req, res, next) => { try { const { id } = parseOrThrow(idSchema, req.params); const { parts } = parseOrThrow(uploadCompleteSchema, req.body); const asset = await completeUpload(id, req.currentUser!._id, parts); await audit(req, "asset.upload", "asset", id, undefined, asset); res.json({ success: true, data: asset, message: asset.status === "ready" ? "Upload ready" : "Upload is processing" }); } catch (error) { next(error); } });

router.get("/orders", async (req, res, next) => { try { res.json({ success: true, data: await listAdminOrders(req.query) }); } catch (error) { next(error); } });
router.get("/orders/:id", async (req, res, next) => { try { const { id } = parseOrThrow(idSchema, req.params); res.json({ success: true, data: await getAdminOrder(id) }); } catch (error) { next(error); } });

router.get("/discounts", async (req, res, next) => { try { const page = Math.max(1, Number(req.query.page) || 1), pageSize = Math.min(100, Math.max(1, Number(req.query.pageSize) || 15)); const filter = req.query.search ? { code: new RegExp(String(req.query.search).replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "i") } : {}; const [items, total] = await Promise.all([DiscountModel.find(filter).sort({ createdAt: -1 }).skip((page - 1) * pageSize).limit(pageSize).lean(), DiscountModel.countDocuments(filter)]); res.json({ success: true, data: { items: items.map((item) => ({ ...item, id: String(item._id) })), page, pageSize, total, pages: Math.max(1, Math.ceil(total / pageSize)) } }); } catch (error) { next(error); } });
router.post("/discounts/generate", (_req, res) => { res.json({ success: true, data: { code: `SAVE-${randomBytes(4).toString("hex").toUpperCase()}` } }); });
router.post("/discounts", async (req, res, next) => { try { const input = parseOrThrow(discountInputSchema, req.body); const item = await DiscountModel.create({ ...input, createdBy: req.currentUser!._id }); await audit(req, "discount.create", "discount", String(item._id), undefined, item.toObject()); res.status(201).json({ success: true, data: item, message: "Discount created" }); } catch (error) { next(error); } });
router.put("/discounts/:id", async (req, res, next) => { try { const { id } = parseOrThrow(idSchema, req.params); const before = await DiscountModel.findById(id).lean(); if (!before) throw new AppError(404, "DISCOUNT_NOT_FOUND", "Discount not found"); const item = await DiscountModel.findByIdAndUpdate(id, parseOrThrow(discountPatchSchema, req.body), { returnDocument: "after", runValidators: true }); await audit(req, "discount.update", "discount", id, before, item?.toObject()); res.json({ success: true, data: item, message: "Discount updated" }); } catch (error) { next(error); } });
router.delete("/discounts/:id", async (req, res, next) => { try { const { id } = parseOrThrow(idSchema, req.params); const item = await DiscountModel.findByIdAndDelete(id); if (!item) throw new AppError(404, "DISCOUNT_NOT_FOUND", "Discount not found"); await audit(req, "discount.delete", "discount", id, item.toObject()); res.json({ success: true, data: null, message: "Discount deleted" }); } catch (error) { next(error); } });

// PRD-compatible aliases; the existing PUT routes remain for backward compatibility.
router.get("/analytics", async (req, res, next) => { try { const allowed = ["day", "week", "month", "six_months", "year"] as const; const period = allowed.includes(req.query.period as typeof allowed[number]) ? req.query.period as typeof allowed[number] : "month"; res.json({ success: true, data: await marketplaceInsights(period, req.query.from ? String(req.query.from) : undefined, req.query.to ? String(req.query.to) : undefined) }); } catch (error) { next(error); } });
router.get("/analytics/themes", async (req, res, next) => { try { res.json({ success: true, data: await themeSales(req.query.from ? String(req.query.from) : undefined, req.query.to ? String(req.query.to) : undefined) }); } catch (error) { next(error); } });
router.patch("/themes/:id", async (req, res, next) => { try { const { id } = parseOrThrow(idSchema, req.params); const before = await getAdminTheme(id); const theme = await updateTheme(id, req.currentUser!._id, parseOrThrow(themePatchSchema, req.body)); await audit(req, "theme.update", "theme", id, before, theme.toObject()); res.json({ success: true, data: await getAdminTheme(id), message: "Theme updated" }); } catch (error) { next(error); } });
router.patch("/discounts/:id", async (req, res, next) => { try { const { id } = parseOrThrow(idSchema, req.params); const before = await DiscountModel.findById(id).lean(); if (!before) throw new AppError(404, "DISCOUNT_NOT_FOUND", "Discount not found"); const item = await DiscountModel.findByIdAndUpdate(id, parseOrThrow(discountPatchSchema, req.body), { returnDocument: "after", runValidators: true }); await audit(req, "discount.update", "discount", id, before, item?.toObject()); res.json({ success: true, data: item, message: "Discount updated" }); } catch (error) { next(error); } });
router.post("/uploads", rateLimit("upload-init", 30, 60_000, true), async (req, res, next) => { try { res.status(201).json({ success: true, data: await initiateUpload(req.currentUser!._id, parseOrThrow(uploadInitSchema, req.body)) }); } catch (error) { next(error); } });
router.delete("/uploads/:id", async (req, res, next) => { try { const { id } = parseOrThrow(idSchema, req.params); await cancelUpload(id, req.currentUser!._id); await audit(req, "asset.cancel", "asset", id); res.json({ success: true, data: null, message: "Upload canceled" }); } catch (error) { next(error); } });

export default router;
